version: "3.9"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.2.0
    container_name: questory-db
    hostname: questory-db
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_volume:/var/lib/mysql
    # 無くても動くが指定しておくとコンテナ停止時にサービスが再起動してくれる
    # https://docs.docker.jp/v19.03/config/container/start-containers-automatically.html
    restart: always
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: questory-api
    environment:
      TZ: Asia/Tokyo
    # tmp/pids/server.pidが残ってたら `A server is already running. ~~` のエラーでrailsを起動できないので事前に消してから、`rails sever` する
    volumes:
      - questory_volume:/app
      - bundle_data:/usr/local/bundle:cached
    ports:
      - "80:3000"
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - db

volumes:
  questory_volume:
  bundle_data:
  mysql_volume:
