default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: questory_api_development

test:
  <<: *default
  database: questory_api_test
.
production:
  <<: *default
  database: questory_api_production
  username: questory_api
  password: <%= ENV["QUESTORY_API_DATABASE_PASSWORD"] %>
